"""Postgres dialect helper. SQLite remains default. Not a lakehouse."""

from __future__ import annotations

SQLITE_TO_POSTGRES = {
    "INTEGER PRIMARY KEY AUTOINCREMENT": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    "INSERT OR IGNORE": "INSERT",
    "INSERT OR REPLACE": "INSERT",
}


def sqlite_ddl_to_postgres(ddl: str) -> str:
    out = ddl
    for src, dst in SQLITE_TO_POSTGRES.items():
        out = out.replace(src, dst)
    return out
